name: pu_material
description: "Componentes y utilidades de Pickme up"

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  svg_flutter: ^0.0.1
  textfield_tags: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
    
  fonts:
    - family: Sansation-bold
      fonts:
        - asset: fonts/Sansation_Bold.ttf
          weight: 700
        # - asset: assets/fonts/Sansation_Light.ttf
        #   weight: 300
        # - asset: assets/fonts/Sansation_Regular.ttf
          style: normal

  module:
    androidX: true
    androidPackage: com.pickmeup.pu_material
    iosBundleIdentifier: com.pickmeup.puMaterial
